:toc:
:toclevels: 4
:imagesdir: ./

= Java for Kids

This Web site contains the early drafts of the book "Java for Kids" by Yakov Fain. The final version will have more detailed explanations. The printed book should be published by http://www.nostarch.com/[No Starch Press] in May of 2015 and can be pre-ordered on http://www.amazon.com/Java-Kids-Yakov-Fain/dp/1593276370/ref=sr_1_5[Amazon]. The publisher has allowed posting this content online so the author can get your comments even before the book goes to print. My son http://instagram.com/yurifain[Yuri Fain] is creating illustrations for this book.

If you find an error in code samples email your comments directly to Yakov at yakovfain@gmail.com or open an issue at https://github.com/yfain/Java4Kids_NoStarchPress_code[code samples repository] on GitHub. 

While this book is written for 12 year old kids and older, adults looking for an easy intro to Java may find this book useful too.  If this material looks too easy for you get my video course "Introduction to Java and Java EE" at http://bit.ly/1HERoVo[Parleys].

== TOC 

This is a short version of  Table of Content of the book "Java For Kids". Publisher: No Starch Press. 

* <<Chapter_1.adoc#,Chapter 1. Your First Java Program>>
* <<Chapter_2.adoc#,Chapter 2. Getting Comfy In IDEA IDE>>
* <<Chapter_3.adoc#,Chapter 3. Meet Classes - the Main Language Constructs>>
* <<Chapter_4.adoc#,Chapter 4. Java Building Blocks>>
* <<Chapter_5.adoc#,Chapter 5. Interfaces, Lambdas, and Anonymous Classes >>
* <<Chapter_6.adoc#,Chapter 6. Access Levels, Collections, Generics, and Multi-Threading >>
* <<Chapter_7.adoc#,Chapter 7. Introduction to GUI with JavaFX>>
* <<Chapter_8.adoc#,Chapter 8. User Interaction in JavaFX>> 
* <<Chapter_9.adoc#,Chapter 9. Error Handling>>
* <<Chapter_10.adoc#,Chapter 10. Creating a Tic-Tac-Toe Game>>
* <<Chapter_11.adoc#,Chapter 11. Working With Files and Serialization>>
* <<Chapter_12.adoc#,Chapter 12. Networking: Downloading Files From the Internet>>
* <<Chapter_13.adoc#,Chapter 13. Creating a Ping-Pong Game>>
* <<Appendix_A.adoc#,Chapter 14. Git for Kids>>

   
 
